name: 'Generate Labels'

on:
  # pull_request:
  #   types: [opened, edited, synchronize]
  push:
    tags:
      - 'v*.*.*'

jobs:
  label:
    name: 'Label PR based on title'
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}