name: Main Release

# on:
#   push:
#     tags:
#       - 'v*.*.*'

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Changelog
        run: |
          npm i generate-changelog -g
          generate-changelog
          changelog > ${{ github.workspace }}/CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          repository: GoodLinker/goodlinker-admin
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - '*'